=== yyangkuble/myproject/springplus/src/com/app/project/sqls/sql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com)-->
<xs:schema xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.springmvcplus.com/schema/sql">
	<xs:simpleType name="ST_text">
		<xs:restriction base="xs:string">
			<xs:enumeration value="//sql text"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="sqls">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="modeName" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="script" maxOccurs="unbounded" minOccurs="0"/>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
				</xs:sequence>
				<xs:element ref="where" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sqlid"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="des" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="描述"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="api" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="key:des"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="script">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="text">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_text">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="if" block="#all">
		<xs:complexType mixed="true">
			<xs:attribute name="if" use="required" type="xs:string"/>
		</xs:complexType>
		
	</xs:element>
	<xs:element name="where">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="script" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="if" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="elseif" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="else" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="elseif" block="#all">
		<xs:complexType mixed="true">
			<xs:attribute name="if" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="else" block="#all">
		<xs:complexType mixed="true">
			<xs:simpleContent>
				<xs:extension base="ST_text">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/user.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="用户" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<sql id="checkTel" des="检查手机是否已经注册">
		select count(*) as telCount from user where tel = #{tel}
	</sql>
	<sql id="selectUserByTel">
		select a.*,b.groupName,b.rongCloudGroupId from user a left join group_ b on a.groupid=b.id where tel = #{tel}
	</sql>
	<!-- 验证登录 -->
	<sql id="login">
		select * from user where tel = #{tel} and password=#{password}
	</sql>
	<!-- 通过电话查询用户id -->
	<sql id="findUserById">
		select a.*,b.groupName,b.rongCloudGroupId from user a left join group_ b on a.groupid=b.id where a.id=#{id}
	</sql>
	<sql id="findUserByIdMessageUsed">
		select name,imgUrl from user where id=#{id}
	</sql>
	<sql id="UserCarPolicyLogByUserId">
		select a.*,b.name as customName from UserCarPolicyLog a join custom b on a.customid=b.id where a.userid=#{userId} order by id desc
	</sql>
	<!-- 
		通过客户id查询用户拜访记录
	 -->
	<sql id="findUserVisitLogByCustomId">
		select * from uservisitlog where customId= #{customId}
	</sql>
	<!-- 查询用户通知 -->
	<sql id="findUserNotifys">
		select * from NotifyMessage where isread=0 and userid=#{userId}
	</sql>
	<!-- 通过id查询用户日程 -->
	<sql id="findUserTripById">
		select * from userTrip where id = #{id}
	</sql>
</sqls>
