=== yyangkuble/myproject/springplus/src/com/app/project/sqls/sql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com)-->
<xs:schema xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.springmvcplus.com/schema/sql">
	<xs:simpleType name="ST_text">
		<xs:restriction base="xs:string">
			<xs:enumeration value="//sql text"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="sqls">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="modeName" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="script" maxOccurs="unbounded" minOccurs="0"/>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element ref="if"/>
					<xs:element ref="elseif"/>
					<xs:element ref="else"/>
				</xs:sequence>
				<xs:element ref="where" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sqlid"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="des" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="描述"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="api" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="key:des"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="script">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="text" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="text">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_text">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="if" block="#all">
		<xs:complexType mixed="true">
			<xs:attribute name="if" use="required" type="xs:string"/>
		</xs:complexType>
		
	</xs:element>
	<xs:element name="where">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="script" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="if" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="elseif" maxOccurs="unbounded" minOccurs="0" />
				<xs:element ref="else" maxOccurs="unbounded" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="elseif" block="#all">
		<xs:complexType mixed="true">
			<xs:attribute name="if" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value=""/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="else" block="#all">
		<xs:complexType mixed="true">
			<xs:simpleContent>
				<xs:extension base="ST_text">
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/custom.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="用户" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<!-- 通过id查询 -->
	<sql id="findCustomById">
		select * from custom where id = #{id}
	</sql>
	<!-- 
C2客户排序
	字母排序(默认)：A~Z~数字、特殊字符
	客户等级:A~D
	生日:依照月1~12，日期从小到大
	最近拜访客户：拜访日程时间从近到远
	久未拜访客户：拜访日程时间从远到近
	年龄:依照1~99,或99~1
	车险到期日:依照最新日期开始
	年缴保费: 从高至低
	年收入：从高到低
	*注：所有排序选项字段为空的，排到最后，选项相同的，都按字母排
	
	
C3客户筛选
	类别:营销,增员,所有类别  customType
	客户等级：A,B,C,D level
	关系: 缘故,转介绍,陌生开发,自定义（把该用户自定义过的选项都列出来）relationship
	生日:1月,2月…12月  birthDay
	车险 : 有,无   car(通过保险结束日期判定)
	年龄 : 可自己选 起始岁数~结束岁数,如15~48   ageStart ageEnd
	年缴保费 : 0~1万,1万~5万,5万~10万,10万~20万,20万以上   根据保费whim判定  whimStart whimEnd
	性别：男,女  sex
	保险观念：医疗型,理财型,综合型,无观念   hope
	
	 -->
	<sql id="selectCoustom">
		select * from custom where userId=#{userId}
		<script>
			if(customType == '营销' || customType == '增员'){
				<text>and customType=#{customType}</text>
			}
			if(level != null){
				<text>and level = #{level}</text>
			}
			if(birthDay != null){
				<text>and month(birthDay)=#{birthDay}</text>
			}
			if(car != null){
				if(car == '有'){
					<text>and carExpireDate is not null and carExpireDate != ''</text>
				}else{
					<text>and carExpireDate is null</text>
				}
			}
			if(ageStart != null && ageEnd != null){
				<text>and age >= #{ageStart} and age <= #{ageEnd}</text>
			}
			if(whimStart != null && whimEnd != null){
				<text>and whim >= #{whimStart} and whim <= #{whimEnd}</text>
			}
			if(sex != null){
				<text>and sex=#{sex}</text>
			}
			if(hope != null){
				<text>and hope=#{hope}</text>
			}
			if(relationship != null){
				<text>and relationship=#{relationship}</text>
			}
		</script>
		<script>
			if(orderType != null){
				if(orderType == 'abc'){
					<text>order by IF(ISNULL(abc),1,0)</text>
				}else if(orderType == 'customlevel'){
					<text>order by IF(ISNULL(level),1,0),abc</text>
				}else if(orderType == 'birthday'){
					<text>order by IF(ISNULL(month(birthDay)),1,0),abc</text>
				}else if(orderType == 'visitLateTime'){
					<text>order by IF(ISNULL(visitLastTime),1,0) desc,abc</text>
				}else if(orderType == 'visitLongTime'){
					<text>order by IF(ISNULL(visitLastTime),1,0),abc</text>
				}else if(orderType == 'age'){
					<text>order by IF(ISNULL(age),1,0),abc</text>
				}else if(orderType == 'carExpireDate'){
					<text>order by IF(ISNULL(carExpireDate),1,0),abc</text>
				}else if(orderType == 'policy'){
					<text>order by IF(ISNULL(policy),1,0) desc,abc</text>
				}else if(orderType == 'yearIncome'){
					<text>order by IF(ISNULL(yearIncome),1,0) desc,abc</text>
				}
			}else{
				<text>order by IF(ISNULL(abc),1,0)</text>
			}
		</script>
	</sql>
</sqls>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/base.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="用户" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<sql id="lastId">
		SELECT LAST_INSERT_ID()
	</sql>
	<!-- 拜访类别 -->
	<sql id="VisitProject">
		select * from visitproject order by orderby
	</sql>
	<!-- 客户保险观念 -->
	<sql id="customhope">
		select * from customhope order by orderby
	</sql>
	<!-- 客户类型 -->
	<sql id="customtype">
		select * from customtype order by orderby
	</sql>
	<!-- 客户排序搜索列表 -->
	<sql id="ordercustom">
		select * from ordercustom order by orderby
	</sql>
	<!-- 通过外键id查询图片列表 -->
	<sql id="imgs">
		select id,imgurl from imgs where foreignKey = #{id} order by id
	</sql>
	<!-- 查询星座 -->
	<sql id="xingzuo">
		select * from xingzuo
	</sql>
	<!-- 查询星座销售推荐 -->
	<sql id="xingzuoSale">
		select a.xingzuo,b.* from xingzuo a,xingzuo_sale b where a.id = b.xingzuoId 
		<if if="xingzuoId != null">
			and xingzuoid=#{xingzuoId}
		</if>
	</sql>
</sqls>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/group.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="用户" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<!-- 查询最新公告 -->
	<sql id="findNewGroupNotice">
		select * from GroupNotice where groupId=#{groupId} order by id desc limit 0,1
	</sql>
	<!-- 查询所有公告 -->
	<sql id="findGroupNotice">
		select * from GroupNotice where 1=1 
			<if if="groupId != null">
				and groupId=#{groupId} 
			</if>
			<if if="id != null">
				and id = #{id}
			</if>
		 order by id desc
	</sql>
	<!-- 通过团队id查询团队信息 -->
	<sql id="selectGroupAllUser">
		select u.id as userid,u.imgUrl,u.groupId,u.tel,u.name as username,u.groupAuth,g.groupName,g.createTime 
		from user u,group_ g where u.groupId=g.id and g.id=#{groupId} order by u.groupAuth
	</sql>
	<!-- 查询团队基本信息 -->
	<sql id="selectGroupInfo">
		select * from group_ where id=#{groupId}
	</sql>
	<!-- 通过组id查询所有日志 -->
	<sql id="groupJournalAll">
		select a.*,b.name as userName,b.imgUrl as userImgUrl from GroupJournal a join user b on a.userid=b.id 
		where 1=1 
		<if if="groupId != null">
			and a.groupId=#{groupId}
		</if>
		<if if="journalId != null">
			and a.id = #{journalId}
		</if>
		<if if="userId != null">
			and a.userid=#{userId}
		</if>
		 order by a.id desc
	</sql>
	<!-- 通过日志id查询点赞 -->
	<sql id="GroupJournalFabulous">
		select a.*,b.name as userName,b.imgUrl as userImgUrl from GroupJournalComment a join user b on a.userid=b.id where journalId = #{journalId} and context='_Fabulous_' order by a.id
	</sql>
	<sql id="personnelPool">
		(select a.visitCustomId,a.visitProject,DATE_FORMAT(a.visitTime,'%c月%e日') as visitTime,b.name as customname from usertrip a join custom b on a.visitCustomId = b.id where a.userid in(select id from user where groupid = #{groupId}) and visittype='增员' and visitproject in('面谈报名','受训','结训','上岗','关系建立')) 
UNION
(select testedcustomid as visitCustomId,DATE_FORMAT(testtime,'%c月%e日') as visitTime,testedname as customname,'性向测验' as visitProject from test_resultlog where testedcustomid in (select distinct a.visitCustomId from usertrip a  where a.userid in(select id from user where groupid = #{groupId}) and visittype='增员' and visitproject in('面谈报名','受训','结训','上岗','关系建立') ))
order by visitCustomId,visitTime
	</sql>
	<!-- 通过日志id查询评论 -->
	<sql id="GroupJournalComment">
		select a.*,b.name as userName,b.imgUrl as userImgUrl from GroupJournalComment a join user b on a.userid=b.id where journalId = #{journalId} and context <> '_Fabulous_' order by a.id
	</sql>
	<!-- 通过团队id查询团队行程 -->
	<sql id="GroupTrip">
		select * from GroupTrip where groupId=#{groupId} order by id
	</sql>
	<!-- 获取测试结果记录 -->
	<sql id="selectTestLogs">
		select a.id,a.testTime,a.testedName,a.score,b.name as testerName from test_resultlog a,user b where a.testerUserId = b.id 
		<if if="testedName != null">
			and a.testedName like '%${testedName}%'
		</if>
		<if if="testerName != null">
			and b.name like '%${testerName}%'
		</if>
		order by a.id desc
	</sql>
	<!-- 日历查询群组 日程 -->
	<sql id="selectGroupTripByDate">
		select * from grouptrip where groupId = #{groupId} and case when startDate is null or startDate ='' then endDate=#{date} else #{date} between startDate and endDate end
	</sql>
	<!-- 日历查询群组 查询一天的，需要带上具体的用户名称 -->
	<sql id="selectGroupTripByOneDate">
		select * from grouptrip where groupId = #{groupId} and case when startDate is null or startDate ='' then endDate=#{date} else #{date} between startDate and endDate end
	</sql>
</sqls>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/a.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="首页" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<!-- 消息数量 A1-->
	<sql id="notifyCount">
		select count(id) as notifyCount from NotifyMessage where toUserId=#{userId} and isread = 0
	</sql>
	<!-- 今日拜访客户 -->
	<sql id="todayVisitCustom">
		select distinct b.name from usertrip a ,custom b where a.visitCustomId = b.id and a.userId= #{userId} and visitDate = curdate()
	</sql>
	<!-- 小秘书提醒 生日 7天内-->
	<sql id="secretaryRemindBirthay">
		select * from ( select id,name,birthday,datediff(concat(DATE_FORMAT(NOW(), '%Y'),right(birthday,6)),curdate()) as daycount,'1' as remindType  from  custom where userId=#{userId}) aa where daycount < 8 and daycount >= 0
	</sql>
	<!-- 小秘书提醒 车险到期-->
	<sql id="secretaryRemindCar">
		select * from(select id,name,carExpireDate,date_sub(carExpireDate,interval 3 month) as toubaoDate,datediff(curdate(),date_sub(date_sub(carExpireDate,interval 3 month),interval 7 day)) as daycount,'2' as remindType from custom where userId=#{userId}) aa where daycount >=0
	</sql>
	<!-- 小秘书提醒 纪念日-->
	<sql id="secretaryRemindImportanceday">
		select * from (select a.id,a.name,b.day,b.context,datediff(curdate(),concat(DATE_FORMAT(NOW(), '%Y'),right(b.day,6))) as daycount,'3' as remindType from custom a join customimportanceday b on a.id=b.customId where a.userId=#{userId}) aa where daycount<4
	</sql>
	<!-- 建议拜访的客户 -->
	<sql id="proposalVisitCustom">
		<script>
			if(type=='birthay'){
				<!-- 近期生日 -->
				<text>select * from ( select id,name,birthday,datediff(concat(DATE_FORMAT(NOW(), '%Y'),right(birthday,6)),curdate()) as daycount,imgPathSmall from  custom where userId=#{userId}) aa where daycount < 61 and daycount >=0 order by daycount</text>
			}else if(type=='healthy'){
				<!-- 健康需求 -->
				<text>select id,name,age,imgPathSmall from custom where userId=#{userId} and age between 25 and 44 and sex = '女' order by age</text>
			}else if(type=='money'){
				<!-- 理财需求 -->
				<text>select id,name,age,imgPathSmall from custom where userId=#{userId} and age between 40 and 54 order by age</text>
			}else if(type=='family'){
				<!-- 家庭保单需求 -->
				<text>select id,name,age,imgPathSmall from custom where userId=#{userId} and age between 30 and 39 order by age</text>
			}else if(type=='longVisit'){
				<!-- 久未拜访 -->
				<text>select * from (select aa.*,bb.id,bb.name,bb.imgPathSmall,datediff(curdate(),aa.visitTime) as daysnovisit from (select a.visitCustomId,max(a.visitTime) as visittime from usertrip a where userid=#{userId} and a.state in(2,3) group by a.visitCustomId) aa join custom bb on aa.visitCustomId = bb.id) aaa where aaa.daysnovisit > 90 order by aaa.daysnovisit desc</text>
			}else if(type=='custionData'){
				<!-- 资料收集 -->
				<text>select * from custom where birthDay is null or birthDay ='' and userid = #{userId}</text>
			}else if(type=='plan'){
				<!-- 资料收集 -->
				<text>
					select aaa.*,bbb.name from(
					select 
					case when usertripid is null then 'plan' else 'trip' end as idtype,
					case when usertripid is null then customid else visitcustomid end as customid
					 from(
					(select distinct a.id as usertripId,a.visitCustomId from usertrip a  where a.userid=#{userId} and a.state=1 and left(a.visittime,7)=left(now(),7)) aa 
					left join 
					(select id as planid ,customId from userplan  where userid=#{userId} and plandate =left(now(),7)) bb
					on aa.visitCustomId=bb.customId
					)
					UNION 
					select 
					case when usertripid is null then 'plan' else 'trip' end as idtype,
					case when usertripid is null then customid else visitcustomid end as customid
					 from(
					(select distinct a.id as usertripId,a.visitCustomId from usertrip a  where a.userid=#{userId} and a.state=1 and left(a.visittime,7)=left(now(),7)) aa 
					right join 
					(select id as planid ,customId from userplan  where userid=#{userId} and plandate =left(now(),7)) bb
					on aa.visitCustomId=bb.customId
					)
					) aaa join custom bbb on aaa.customid=bbb.id
				</text>
			}
		</script>
		
	</sql>
	<sql id="plancustomlist">
		select aaa.*,bbb.name,bbb.level from(
		select 
		case when usertripid is null then 'plan' else 'trip' end as idtype,
		case when usertripid is null then plandate else tripDate end as tripdate,
		case when usertripid is null then customid else visitcustomid end as customid
		 from(
		(select distinct a.id as usertripId,a.visitCustomId,left(a.visitDate,7) as tripDate from usertrip a  where a.userid=#{userId} and a.state=1 and left(a.visittime,7)='${month}') aa 
		left join 
		(select id as planid ,customId,plandate from userplan  where userid=#{userId} and plandate ='${month}') bb
		on aa.visitCustomId=bb.customId
		)
		UNION 
		select 
		case when usertripid is null then 'plan' else 'trip' end as idtype,
		case when usertripid is null then plandate else tripDate end as tripdate,
		case when usertripid is null then customid else visitcustomid end as customid
		 from(
		(select distinct a.id as usertripId,a.visitCustomId,left(a.visitDate,7) as tripDate from usertrip a  where a.userid=#{userId} and a.state=1 and left(a.visittime,7)='${month}') aa 
		right join 
		(select id as planid ,customId,plandate from userplan  where userid=#{userId} and plandate ='${month}') bb
		on aa.visitCustomId=bb.customId
		)
		) aaa join custom bbb on aaa.customid=bbb.id
	</sql>
	
	<sql id="plancustomcount">
		select bbb.level,count(bbb.level) as customcount from(
		select 
		case when usertripid is null then 'plan' else 'trip' end as idtype,
		case when usertripid is null then plandate else tripDate end as tripdate,
		case when usertripid is null then customid else visitcustomid end as customid
		 from(
		(select distinct a.id as usertripId,a.visitCustomId,left(a.visitDate,7) as tripDate from usertrip a  where a.userid=#{userId} and a.state=1 and left(a.visittime,7)='${month}') aa 
		left join 
		(select id as planid ,customId,plandate from userplan  where userid=#{userId} and plandate ='${month}') bb
		on aa.visitCustomId=bb.customId
		)
		UNION 
		select 
		case when usertripid is null then 'plan' else 'trip' end as idtype,
		case when usertripid is null then plandate else tripDate end as tripdate,
		case when usertripid is null then customid else visitcustomid end as customid
		 from(
		(select distinct a.id as usertripId,a.visitCustomId,left(a.visitDate,7) as tripDate from usertrip a  where a.userid=#{userId} and a.state=1 and left(a.visittime,7)='${month}') aa 
		right join 
		(select id as planid ,customId,plandate from userplan  where userid=#{userId} and plandate ='${month}') bb
		on aa.visitCustomId=bb.customId
		)
		) aaa join custom bbb on aaa.customid=bbb.id
		group by level
	</sql>
</sqls>

=== yyangkuble/myproject/springplus/src/www/springmvcplus/com/sqls/plus.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="框架初始化" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	
	<sql id="select_api_by_modename">
		select * from sys_api where modename=#{modename}
	</sql>
	
	<sql id="log_select_by_where">
		select * from sys_log ${where} order by updatetime desc
	</sql>
	
	<sql id="watch_request">
		select d.id as requestid,d.url,d.usetime,d.starttime,d.sqlallusetime,d.sqlcount,(d.usetime-d.sqlallusetime) as javausetime from (select c.id,c.url,c.usetime,c.starttime,sum(sqlusetime) as sqlallusetime,count(sqlusetime) as sqlcount from (select a.id,a.url,a.starttime,(a.endtime-a.starttime) as usetime,(b.endtime-b.starttime) as sqlusetime from sys_request a join sys_request_sql b on a.id=b.request_id) c group by c.starttime,c.url,c.usetime,c.id) d
	</sql>
	<sql id="findApiModeName">
		select distinct modename from sys_api
	</sql>
	<sql id="findApiByModename">
		select * from sys_api where modename = #{modename}
	</sql>
	<sql id="weblogin">
		select * from user where username=#{username} and password=#{password}
	</sql>
	<sql id="checkUserName">
		select count(*) from user where username=#{username}
	</sql>
</sqls>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/user_role_menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="用户角色菜单" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<!-- 菜单查询 -->
	<sql id="menu_all">
		select * from sys_menu
	</sql>
	<!-- 按照userid查询子菜单 -->
	<sql id="menu_by_parentid_and_userid">
		select c.* from sys_user_role a join sys_role_menu b on a.roleid=b.roleid join sys_menu c on b.menuid=c.id 
		where c.parentid=#{parentid} and a.userid=#{userid} order by c.orderby
	</sql>
	<!-- 通过父id获取子菜单最大的排序代码 -->
	<sql id="menu_get_max_order_code_by_parentid">
		select max(orderby)+20 from sys_menu where parentid=#{parentid}
	</sql>
	<!--  查询全部角色 -->
	<sql id="role_all">
		select * from sys_role
	</sql>
	<!-- 通过角色id查询菜单列表 -->
	<sql id="menuid_by_roleid">
		select menuid from sys_role_menu where roleid=#{roleid}
	</sql>
	<!-- 通过roleid删除所有菜单 -->
	<sql id="delete_sys_role_menu">
		delete from sys_role_menu where roleid=#{roleid}
	</sql>
	<!-- 通过条件查询用户 -->
	<sql id="user_select_by_where">
		select * from user ${where} order by addtime desc
	</sql>
	<!-- 检查用户名是否重复 -->
	<sql id="user_check_username_isused">
		select count(*) from user where username=#{username}
	</sql>
	<!-- 通过userid查询角色 -->
	<sql id="role_slect_by_userid">
		select roleid from sys_user_role where userid=#{userid}
	</sql>
	<!-- 测试查询通过条件 -->
	<sql id="test_select_by_where">
		select * from sys_test 
		<where>
			<if if="guanjianci">
				username like '%${guanjianci}%' or tel like '%${guanjianci}%' or name like '%${guanjianci}%'
			</if>
		</where>
		order by addtime desc
	</sql>
	<!-- 查询测试表username是否重复 -->
	<sql id="test_check_username_isused">
		select count(*) from sys_test where username=#{username}
	</sql>
	<!-- 通过parentid查询菜单 -->
	<sql id="menu_by_parentid">
		select * from sys_menu where parentid=#{parentid} order by orderby
	</sql>
</sqls>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/payAsk.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="用户" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	<sql id="findPayAsks">
		select aa.*,bb.name as askUserName,cc.name as answerUserName,bb.imgUrl as askUserImg,cc.imgUrl as answerUserImg from (
		select a.*,case when b.id is null then 0 else 1 end as ispay from 
		payask a 
			<if if="mylisens != 'yes'"> left </if>
		 join payasklog b on a.id=b.payAskId and b.userId=#{userId}
		) aa join user bb on aa.askuserid=bb.id left join user cc on aa.answerUserid=cc.id where 1=1
			<if if="myAsks == 'yes'">
				and aa.askUserId=#{userId}
			</if>
		<if if="orderby == null">
			order by aa.answerTime desc
		</if>
		<elseif if="orderby == 'yesNumber'">
			order by aa.yesNumber desc
		</elseif>
		<elseif if="orderby == 'askTime'">
			order by aa.askTime desc
		</elseif>
		<else>
			order by aa.answerTime desc
		</else>
		
	</sql>
	
	
	<!-- 问答 -->
	<!-- 问答的列表 -->
	<sql id="askList">
		select a.id as askId,a.title as askTitle,a.context as askContext,a.answerCount,a.allYesCount,a.createTime as askCreateTime,b.answerType,b.createTime as answerCreateTime,b.yesCount as answerYesCount,b.fileUrls as answerFileUrl,b.context as answerContext,b.commentCount as answerCommentCount,c.imgUrl as askUserImgUrl,c.name as askUserName,d.imgUrl as answerUserImgUrl,d.name as answerUserName,d.iszhuanjia from ask a left join answer b on a.bestAnswerId=b.id join user c on a.userId=c.id left join user d on b.userId=d.id 
		where 1=1
		<if if="askType != null">
			and a.askType=#{askType}
		</if>
		<if if="askUserId != null">
			and a.userId=#{askUserId}
		</if>
		<if if="askId != null">
			and a.id=#{askId}
		</if>
		<if if="sort == 'bestnew'">
			order by a.createTime desc
		</if>
		<else>
			order by a.allyescount desc
		</else>
	</sql>
	<!-- 回答列表 -->
	<sql id="answerList">
		select b.id as answerId,b.answerType,b.createTime as answerCreateTime,b.yesCount as answerYesCount,b.fileUrls as answerFileUrl,b.context as answerContext,b.commentCount as answerCommentCount,d.imgUrl as answerUserImgUrl,d.name as answerUserName,d.iszhuanjia from  answer b  join user d on b.userId=d.id
		 where b.askId = #{askId} and b.id <> (select bestAnswerId from ask where id=#{askId}) order by d.iszhuanjia desc,b.yesCount desc,b.createTime desc
	</sql>
	<!-- 查询我的问答列表 -->
	<sql id="myAnswerAskList">
		select a.id as askId,a.title as askTitle,a.context as askContext,a.answerCount,a.allYesCount,a.createTime as askCreateTime,c.imgUrl as askUserImgUrl,c.name as askUserName from ask a  join user c on a.userId=c.id
		where a.id in(select distinct askId from answer where userid=#{userId}) 
	</sql>
	<!-- 我的回答列表 -->
	<sql id="myAnswerList">
		select case when a.bestAnswerId is not null then 1 else 0 end as isbestAnswer,b.id as answerId,b.answerType,b.createTime as answerCreateTime,b.yesCount as answerYesCount,b.fileUrls as answerFileUrl,b.context as answerContext,b.commentCount as answerCommentCount,d.imgUrl as answerUserImgUrl,d.name as answerUserName,d.iszhuanjia 
		from  answer b  join user d on b.userId=d.id left join ask a on b.id=a.bestAnswerId
		 where b.askId = #{askId} and b.userId=#{userId}  order by isbestAnswer desc,b.yesCount desc,b.createTime desc
	</sql>
	<sql id="answerComment">
		(select a.createTime,b.imgUrl as userImgUrl,b.name as username,a.context,'comment' as type from answercomments a join user b on a.userId=b.id where a.answerId=#{answerId} order by a.id desc )
		union all
		(select a.createTime,b.imgUrl as userImgUrl,b.name as username,'' as context,'zhan' as type from answeryes a join user b on a.userId=b.id where a.answerId=#{answerId} order by a.id desc )
	</sql>
	
</sqls>

=== yyangkuble/myproject/springplus/src/com/app/project/sqls/me.xml
<?xml version="1.0" encoding="UTF-8"?>
<sqls modeName="我的" xmlns="http://www.springmvcplus.com/schema/sql" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="http://www.springmvcplus.com/schema/sql sql.xsd">
	
	<sql id="customcount" des="查询客户数量">
		(select b.level,count(b.id) as customCount from user a join custom b on a.id=b.userId where a.id=#{userId} group by level order by b.level)
UNION ALL
(select 'all' as level,count(b.id) as customCount from user a join custom b on a.id=b.userId where a.id=#{userId})
	</sql>
	
	<sql id="selectUserYejiByMonth" des="根据月份查询业绩">
		select * from userYeji where yejiDate=#{yejiDate} and userId=#{userId}
	</sql>
	<sql id="selectVisitCount" des="查询访量">
		select count(*) as visitCount from usertrip where userId=#{userId} and left(visitDate,7) = #{yejiDate}
	</sql>
	
	<sql id="chat1">
		select aa.yejiDate,cast(right(aa.yejiDate,2) as SIGNED INTEGER) as x,salary/visitcount as y from 
		(select yejiDate,salary from useryeji where userid= #{userId} and yejiDate between concat(left(now(),5),'01') and left(now(),7) order by yejiDate) aa ,
		(select left(visitDate,7) as visitmonth,count(*) as visitcount from usertrip where userId=#{userId} and left(visitDate,7) between concat(left(now(),5),'01') and left(now(),7) group by visitmonth order by visitmonth) bb
		where aa.yejiDate = bb.visitmonth
	</sql>
	<sql id="chat2">
		select yejiDate,cast(right(yejiDate,2) as SIGNED INTEGER) as x,salary as y from useryeji where userid= #{userId} and yejiDate between concat(left(now(),5),'01') and left(now(),7) order by yejiDate
	</sql>
	
	<!-- 排名 -->
	<!-- 访量排名 -->
	<sql id="visitCountRanking">
		SELECT @rownum:=@rownum+1 rownum,aa.userId,aa.visitmonth,aa.visitcount From(
		select @rownum:=0,userid,left(visitDate,7) as visitmonth,count(*) as visitcount from usertrip where left(visitDate,7) = #{yejiDate}  group by userId order by visitcount desc
		) aa
		<if if="userId != null">
			where userId = #{userId}
		</if>
	</sql>
	<sql id="visitCountRankingCount">
		select count(*) from(
		select userid,count(*) as visitcount from usertrip where left(visitDate,7) = #{yejiDate}  group by userId 
		) aa
	</sql>
	<!-- 件数 -->
	<sql id="policyNumberRanking">
		SELECT @rownum:=@rownum+1 rownum,aa.userId,aa.policyNumber From(
		select @rownum:=0,userId,policyNumber from useryeji where yejidate=#{yejiDate} order by policyNumber desc
		) aa
		<if if="userId != null">
			where userId = #{userId}
		</if>
	</sql>
	<sql id="policyNumberAndPremiumRankingCount">
		select count(*) from useryeji where yejidate=#{yejiDate} 
	</sql>
	<!-- 保费 -->
	<sql id="premiumRanking">
		SELECT @rownum:=@rownum+1 rownum,aa.userId,aa.premium From(
		select @rownum:=0,userId,premium from useryeji where yejidate=#{yejiDate} order by policyNumber desc
		) aa
		<if if="userId != null">
			where userId = #{userId}
		</if>
	</sql>
	
	<!-- 访量排名 -->
	<sql id="visitCountRankingTop">
		SELECT @rownum:=@rownum+1 ranking,aa.userId,aa.visitmonth,aa.visitcount,bb.name,bb.company From(
		select @rownum:=0,userid,left(visitDate,7) as visitmonth,count(*) as visitcount from usertrip where left(visitDate,7) = left(now(),7)  group by userId order by visitcount desc
		) aa,user bb where aa.userId = bb.id limit 0,30
	</sql>
	
	<sql id="updateSelectUseryeji">
		select *,cast(right(yejiDate,2) as SIGNED INTEGER) as yejimonth from useryeji where userId = #{userId} and left(yejiDate,4)=left(now(),4) order by yejiDate desc
	</sql>
	
</sqls>
